name: CI

on:
  pull_request:
    branches:
    - development
    - '[0-9]+.[0-9]+.x'

  # Run CI also on push to master
  push:
    branches:
    - master

env:
  REPO: quay.io
  REPO_NAME: nuclio
  NUCLIO_LABEL: 1.6.15
  NAMESPACE: nuclio
  NUCLIO_GO_TEST_TIMEOUT: "30m"

jobs:

  test_k8s_nuctl:
    name: Test Kubernetes nuctl
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: azure/setup-helm@v1
      with:
        version: "v3.3.4"

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: "v1.15.1"
        kubernetes version: "v1.17.9"
        driver: docker
        github token: ${{ github.token }}
        start args: '--addons registry --addons ingress'

    - name: Post minikube setup
      run: |

        # redirect $(minikube ip):5000 -> localhost:5000
        docker run --rm --detach --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000"
        minikube kubectl -- config view --flatten > kubeconfig_flatten

    - name: Load nuclio docker images
      run: |

        make pull-docker-images

        # activate minikube docker
        eval $(minikube -p minikube docker-env)

        make pull-docker-images

    - name: Export env
      run: |
        echo "NUCTL_EXTERNAL_IP_ADDRESSES=$(minikube ip)" >> $GITHUB_ENV
        echo "NUCTL_REGISTRY=localhost:5000" >> $GITHUB_ENV
        echo "NUCLIO_DASHBOARD_DEFAULT_ONBUILD_REGISTRY_URL=$REPO" >> $GITHUB_ENV
        echo "NUCTL_NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        echo "KUBECONFIG=$(pwd)/kubeconfig_flatten" >> $GITHUB_ENV
        echo "NUCLIO_TEST_KUBE_DEFAULT_INGRESS_HOST=nuclio-test-function-host.info" >> $GITHUB_ENV
        echo "NUCTL_DEFAULT_SERVICE_TYPE=NodePort" >> $GITHUB_ENV

    - name: Install nuclio helm chart
      run: |
        minikube kubectl -- create namespace ${NAMESPACE}
        cat test/k8s/ci_assets/helm_values.yaml \
          | envsubst \
          | helm install --debug --wait --namespace ${NAMESPACE} -f - nuclio hack/k8s/helm/nuclio/

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    - name: Run nuctl k8s tests
      run: |

        # write function host to /etc/hosts
        echo "${NUCTL_EXTERNAL_IP_ADDRESSES} ${NUCLIO_TEST_KUBE_DEFAULT_INGRESS_HOST}" | sudo tee -a /etc/hosts

        # run test
        make test-k8s-nuctl
