name: CI

on:
  pull_request:
    branches:
      - development
      - 1.1.x
      - 1.3.x

env:
  REPO: quay.io
  REPO_NAME: nuclio
  NUCLIO_LABEL: ${{ github.run_number }}
  NAMESPACE: nuclio

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint
        run: make lint

  test_short:
    name: Test short
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run short test suites
        run: make test-short

  build_nuctl:
    name: Build nuctl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"

      - name: Build
        run: |
          make nuctl
          sudo mv $(go env GOPATH)/bin/nuctl-${NUCLIO_LABEL}-linux-amd64 nuctl
          sudo chmod +x nuctl
          ./nuctl version
        env:
          NUCLIO_NUCTL_CREATE_SYMLINK: false

      - uses: actions/upload-artifact@v1
        with:
          name: nuctl-bin
          path: nuctl

  build_docker_images:
    name: Build nuclio docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # since github-actions gives us 14G only, and fill it up with some garbage
      # we will free up some space for us (~2GB)
      - name: Freeing some disk space
        run: docker system prune --all --force

      - name: Build
        run: make docker-images
        env:
          NUCLIO_DOCKER_REPO: ${{ env.REPO }}/${{ env.REPO_NAME }}

      # Clean build leftovers
      - name: Post build cleanup
        run: docker system prune --force

      - name: Save
        run: |
          # list built images
          # join with " "
          # save docker images
          # compress using pigz (use fast, the difference is insignificant)
          docker images \
              --filter="reference=${REPO}/${REPO_NAME}/*:${NUCLIO_LABEL}*" \
              --format "{{ .Repository }}:{{ .Tag }}" \
            | xargs docker save \
            | pigz --fast > nuclio_docker_images.tar.gz

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: nuclio-docker-images
          path: nuclio_docker_images.tar.gz

  test_k8s:
    name: Test Kubernetes
    runs-on: ubuntu-latest
    needs:
      - build_docker_images
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1
        with:
          version: "v3.1.2"

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: "v1.9.2"
          kubernetes version: "v1.17.3"
          github token: ${{ github.token }}

      - name: Fetch nuclio docker images
        uses: actions/download-artifact@v1
        with:
          name: nuclio-docker-images

      - name: Prepare k8s cluster
        run: |
          kubectl create namespace ${NAMESPACE}
          docker run -d -p 5000:5000 registry:2
          docker load -i nuclio-docker-images/nuclio_docker_images.tar.gz

      - name: Install nuclio helm chart
        run: |
          cat test/k8s/ci_assets/helm_values.yaml \
            | envsubst \
            | helm install --debug --wait --namespace ${NAMESPACE} -f - nuclio hack/k8s/helm/nuclio/

      - name: Run test
        run: |
          set -o pipefail
          make test-nuctl-k8s 2>&1 | tee test-nuctl-k8s-${NUCLIO_LABEL}.log
        env:
          NUCLIO_DASHBOARD_DEFAULT_ONBUILD_REGISTRY_URL: ${{ env.REPO }}
          NUCTL_REGISTRY: "localhost:5000"

      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: k8s test results
          path: test-nuctl-k8s-${{ env.NUCLIO_LABEL }}.log
        if: ${{ always() }}

  test_docker:
    name: Test Docker
    runs-on: ubuntu-latest
    needs:
      - build_docker_images
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Fetch nuclio docker images
        uses: actions/download-artifact@v1
        with:
          name: nuclio-docker-images

      - name: Prepare
        run: |
          docker load -i nuclio-docker-images/nuclio_docker_images.tar.gz

      - name: Run test
        run: |
          set -o pipefail
          make test-nuctl-docker 2>&1 | tee test-nuctl-docker-${NUCLIO_LABEL}.log

      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: k8s test results
          path: test-nuctl-docker-${{ env.NUCLIO_LABEL }}.log
        if: ${{ always() }}

  test_integration:
    name: Test Integration
    runs-on: ubuntu-latest
    needs:
      - build_docker_images
    steps:
      - uses: actions/checkout@v2

      - name: Fetch nuclio docker images
        uses: actions/download-artifact@v1
        with:
          name: nuclio-docker-images

      - name: Load docker images
        run: |
          docker system prune --all --force
          docker load -i nuclio-docker-images/nuclio_docker_images.tar.gz

      - name: Run test
        run: |
          set -o pipefail
          make test 2>&1 | tee test-integration-${NUCLIO_LABEL}.log
          sudo journalctl -u docker.service > docker_service.log
        env:
          NUCLIO_TEST_UNDOCKERIZE_TIMEOUT: 20m

      - uses: actions/upload-artifact@v1
        with:
          name: docker test results
          path: test-integration-${{ env.NUCLIO_LABEL }}.log
        if: ${{ always() }}

      - uses: actions/upload-artifact@v1
        with:
          name: docker service log
          path: docker_service.log
        if: ${{ always() }}
