name: Run action and validate environment

on:
  pull_request:
    branches:
      - development

env:
  NUCLIO_LABEL: latest
  FUNCTION_NAME: test-function
  NAMESPACE: nuclio
  NUCLIO_NUCTL_CREATE_SYMLINK: false
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  import_stable:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install Go
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.11.0'

      # Install helm
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.1.2'

      - name: Build nuctl
        run: |
          make nuctl
          sudo mv $(go env GOPATH)/bin/nuctl-$NUCLIO_LABEL-linux-amd64 nuctl
          sudo chmod +x nuctl
          ./nuctl version

      - name: Build nuctl + nuclio services
        run: |
          make dashboard controller handler-builder-golang-onbuild
          docker save -o nuclio-services.tar.gz \
            quay.io/nuclio/handler-builder-golang-onbuild:latest-amd64-alpine \
            quay.io/nuclio/controller:latest-amd64 \
            quay.io/nuclio/dashboard:latest-amd64

      # Setup minikube + k8s
      - uses: manusa/actions-setup-minikube@v1.0.1
        with:
          minikube version: 'v1.9.0'
          kubernetes version: 'v1.17.3'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare cluster
        run: |
          kubectl create namespace $NAMESPACE
          docker run -d -p 5000:5000 registry:2
          docker load -i nuclio-services.tar.gz

      - name: Install nuclio using helm
        run: |
          helm install \
            --debug \
            --wait \
            --namespace $NAMESPACE \
            --set controller.image.tag=$NUCLIO_LABEL-amd64 \
            --set dashboard.image.tag=$NUCLIO_LABEL-amd64 \
            --set dashboard.baseImagePullPolicy=Never \
            nuclio hack/k8s/helm/nuclio/

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2

      - name: Deploy function
        run: |
          ./nuctl deploy $FUNCTION_NAME \
            --path https://raw.githubusercontent.com/nuclio/nuclio/master/hack/examples/golang/helloworld/helloworld.go \
            --registry localhost:5000 \
            --run-registry localhost:5000 \
            --namespace $NAMESPACE \
            --no-pull

      - name: Invoke function
        run: |
          ./nuctl invoke $FUNCTION_NAME \
            --namespace $NAMESPACE
